<?php
/**
 * Module file for Gen Notes
 */

/**
 * Implements hook_form_FORM_ID_alter().
 */
function gen_notes_form_notes_node_form_alter(&$form, &$form_state, $form_id) {
  //If this is a new note
  if ($form['type']['#value'] == 'notes' && is_null($form['nid']['#value'])) {
    //Get url parameters
    $args = arg();
    $params = drupal_get_query_parameters();
    // If using modal...
    if (count($args) == 5 && $args[3] == 'ajax') {
      $entity_id = (int) $args[4];
    }
    // If not using modal...
    // If id is passed as url parameter...
    else if (count($args) == 4) {
      $entity_id = (int) $args[3];
    }
    // If id is passed in query string...
    else if (isset($params['field_entity_assoc_id'])) {
      $entity_id = (int) $params['field_entity_assoc_id'];
    }
    // Set default value for field_assoc_entity_id.
    if ($entity_id) {
      $form['field_assoc_entity_id'][LANGUAGE_NONE][0]['target_id']['#default_value'] = $entity_id;
    }
  }
}

/**
 * Implements hook_theme().
 */
function gen_notes_theme($existing, $type, $theme, $path) {
  return array(
    'node__notes' => array(
      'render element' => 'content',
      'template' => 'node--notes',
      'base hook' => 'node',
      'path' => drupal_get_path('module', 'gen_notes') . '/templates',
    )
  );
}

/**
 * Implements hook_preprocess_node().
 */
function gen_notes_preprocess_node(&$variables) {
  if ($variables['type'] == 'notes') {
    $destination = drupal_get_destination();
    $querystring = array(
      'field_entity_assoc_id' => $variables['node']->nid,
      $destination,
    );
    if (user_access('create person content')) {
      ctools_include('ajax');
      ctools_include('modal');
      ctools_add_js('ajax-responder');
      // Add CTools' javascript to the page with the block.
      ctools_modal_add_js();
      // return a ctools modal text button.
      $variables['modal_button'] =  ctools_modal_text_button(
        t('Edit'),
        url('node/' . $variables['node']->nid . '/edit/nojs/' . $variables['field_assoc_entity_id'][0]['target_id']),
        t("Show the 'Edit Notes' form"),
        'btn btn-default modal-buttons'
      );

      $variables['nonmodal_button'] = '<div>' . l(
        t('Edit'),
        'node/' . $variables['node']->nid . '/edit',
        array('attributes' => array(
                'class' => array(
                  'btn',
                  'btn-default',
                  'nonmodal-buttons'
                )
              ),
              'query' => $querystring,
              )
      ) . '</div>';
    }
  }
}
